
export default new Map([
["src/content/blog/living/cara-menyimpan-sayuran-agar-tetap-segar-lebih-lama.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fliving%2Fcara-menyimpan-sayuran-agar-tetap-segar-lebih-lama.mdx&astroContentModuleFlag=true")],
["src/content/blog/tech/apa-itu-hot-swap-keyboard-mechanical.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftech%2Fapa-itu-hot-swap-keyboard-mechanical.mdx&astroContentModuleFlag=true")],
["src/content/blog/tech/apa-itu-keyboard-mechanical.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftech%2Fapa-itu-keyboard-mechanical.mdx&astroContentModuleFlag=true")],
["src/content/blog/tech/cara-membersihkan-keyboard-mekanik-yang-benar.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftech%2Fcara-membersihkan-keyboard-mekanik-yang-benar.mdx&astroContentModuleFlag=true")],
["src/content/blog/tech/cara-memilih-keyboard-mechanical-pemula.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftech%2Fcara-memilih-keyboard-mechanical-pemula.mdx&astroContentModuleFlag=true")],
["src/content/blog/tech/cara-pilih-keyboard-mechanical.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftech%2Fcara-pilih-keyboard-mechanical.mdx&astroContentModuleFlag=true")],
["src/content/blog/tech/mechanical-keyboard-vs-membrane.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftech%2Fmechanical-keyboard-vs-membrane.mdx&astroContentModuleFlag=true")],
["src/content/blog/tech/perbedaan-red-switch-brown-switch-blue-switch.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftech%2Fperbedaan-red-switch-brown-switch-blue-switch.mdx&astroContentModuleFlag=true")]]);
		